name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality:
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Install required PHP version"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"

      - name: show PHP version
        run: php -v

      - name: install dependencies
        run: composer install --no-interaction

      - name: static analyze
        run: ./vendor/bin/phpstan

      - name: tests
        run: ./vendor/bin/phpunit
